steps:
  - name: 'node:18.19.0'
    entrypoint: 'npm'
    args: ['install']

  - name: 'node:18.19.0'
    entrypoint: 'npm'
    args: ['run', 'create-env']
    secretEnv: ['TEST']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--project=$PROJECT_ID', '--quiet']

timeout: '1600s'

availableSecrets:
  secretManager:
    - versionName: 'projects/$PROJECT_ID/secrets/TEST/versions/latest'
      env: 'TEST'