# name: Deploy
# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     name: Deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2

#       - name: Setup Node.js environment
#         uses: actions/setup-node@v2
#         with:
#           node-version: 18

#       - name: Install dependencies and build
#         run: |
#           npm ci
#           npm run build

#       - name: Setup Heroku
#         uses: akhileshns/heroku-deploy@v3.12.12 # This action will handle Heroku deployment.
#         with:
#           heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#           heroku_app_name: "<YOUR_HEROKU_APP_NAME>" # Replace with your Heroku app name
#           heroku_email: "<YOUR_HEROKU_EMAIL>" # Replace with your Heroku email
