# name: Deploy
# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     name: Deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2

#       - name: Setup GCloud
#         uses: google-github-actions/setup-gcloud@v0.2.0
#         with:
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           export_default_credentials: true

#       - name: Trigger cloud build
#         run: gcloud builds submit --config ./cloudbuild.yaml --project=${{ secrets.GCP_PROJECT_ID }} .
