name: Pull Request CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"

jobs:
  ci:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ">18.17.0"
          cache: "npm"

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Lint
        run: npm run lint

      - name: Build
        run: yarn build
        env:
          OPENAI_API_KEY: ""
